In [3]:
# Importing libraries
import numpy as np

In [3]:
# 1. Create a 1D array of numbers from 0 to 9.

In [6]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#2. Create a 3×3 numpy array of all True’s

In [9]:
array = np.full((3, 3), True)
array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
# 3. Given an array as input, print only odd numbers as output

In [34]:
arr1 = np.array([3, 5, 6, 7])
indices = np.where(np.logical_not(arr1 % 2 == 0))[0].tolist()

arr2 = np.take(arr1, indices)
print(arr2.tolist())

[3, 5, 7]


In [ ]:
# 4. Replace all odd numbers in arr with -2

In [36]:
arr1 = np.array([3, 5, 6, 7])
arr1 = np.where(np.logical_not(arr1 % 2 == 0), -2, arr1)
print(arr1)

[-2 -2  6 -2]


In [ ]:
# 5. How to reshape an array?

In [51]:
# numpy.reshape(array, shape) : shapes an array without changing data of array.

arr = np.array([1, 2, 3, 4])
arr1 = arr.reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [52]:
# 6. Convert a 1D array to a 2D array with 2 rows

In [73]:
# 7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , 
#    create  new array b from a such that b includes all odd numbers and 4 multiples. 

In [93]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
indexes = np.where((a % 2 == 1) | (a % 4 == 0))[0].tolist()
b = [a[i] for i in indexes]
print(b)

[1, 3, 4, 5, 7, 8, 9]


In [42]:
# 8. Given array, check if there are any null values and print them out. 

In [48]:
arr = np.array([1, 2, np.nan, 4])

nan_indices = np.where(np.isnan(arr))[0].tolist()

for i in nan_indices:
    print(arr[i])


nan


In [104]:
# 9. How to replace all missing values with 0 in a numpy array?

In [57]:
arr = np.array([1, 2, np.nan, 4])
zeroes = [0, 0, 0, 0]
arr1 = np.where(np.isnan(arr),  zeroes, arr)

print(arr1)

[1. 2. 0. 4.]


In [105]:
# 10. How to find the count of each unique number in a NumPy array?

In [114]:
arr = np.array([1, 2, 2, 4 ,5])
(el, counts) = np.unique(arr, return_counts=True)
frequencies = np.array((el, counts)).T
frequencies

array([[1, 1],
       [2, 2],
       [4, 1],
       [5, 1]])

In [115]:
# 11. How to convert a numeric to a categorical (text) array?

In [58]:
arr = np.array([1, 2, 3, 4])
arr1 = arr.astype(str)
arr1

array(['1', '2', '3', '4'], dtype='<U21')

In [116]:
# 12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. 
#.    Exclude the elements which are divisible by both. 

In [25]:
arr = np.arange(99, 300)
indices = np.where(np.logical_and(arr % 5 == 0, arr % 7 == 0))[0].tolist()

# deleting elements divisble by both
arr1 = np.delete(arr, indices)

indices = np.where(np.logical_or(arr % 5 == 0, arr % 7 == 0))[0].tolist()

# creating a new array consisting of elements divisible by 5 or 7
arr2 = np.take(arr, indices)

print(list(arr2))

[100, 105, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 140, 145, 147, 150, 154, 155, 160, 161, 165, 168, 170, 175, 180, 182, 185, 189, 190, 195, 196, 200, 203, 205, 210, 215, 217, 220, 224, 225, 230, 231, 235, 238, 240, 245, 250, 252, 255, 259, 260, 265, 266, 270, 273, 275, 280, 285, 287, 290, 294, 295]


In [27]:
# 13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [28]:
arr = [1, 2, 3, 4]
reverse_arr = arr[::-1]

print(reverse_arr)

[4, 3, 2, 1]
